# Generated by Django 2.1 on 2019-05-17 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hourly_wage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('hourly_wage', models.PositiveIntegerField(null=True, verbose_name='時給')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paid_leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('paid_leave_date', models.DateField(null=True, verbose_name='有給休暇日')),
                ('memo', models.CharField(blank=True, max_length=300, null=True, verbose_name='メモ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Time_is_moneyge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('morning_word', models.CharField(blank=True, max_length=150, null=True, verbose_name='おはようの一言')),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('morning_overtime', models.DurationField(null=True)),
                ('evening_word', models.CharField(blank=True, max_length=150, null=True, verbose_name='お疲れ様の一言')),
                ('end_datetime', models.DateTimeField(auto_now_add=True)),
                ('evening_overtime', models.DurationField(null=True)),
                ('overtime', models.DurationField(null=True)),
                ('todays_overtime', models.DurationField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
