# Generated by Django 2.1 on 2019-05-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_is_moneyge',
            name='working_time',
            field=models.DurationField(null=True),
        ),
    ]
