# Generated by Django 2.1 on 2019-02-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0004_auto_20190210_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_is_moneyge',
            name='morning_overtime',
            field=models.DurationField(null=True),
        ),
    ]
