# Generated by Django 2.1 on 2019-02-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0005_auto_20190210_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_is_moneyge',
            name='word',
        ),
        migrations.AddField(
            model_name='time_is_moneyge',
            name='morning_word',
            field=models.CharField(max_length=150, null=True, verbose_name='今朝の一言'),
        ),
    ]
