# Generated by Django 2.1 on 2019-02-11 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0006_auto_20190210_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_is_moneyge',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
