# Generated by Django 2.1 on 2019-02-16 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0008_auto_20190214_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_is_moneyge',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='time_is_moneyge',
            name='evening_overtime',
        ),
        migrations.RemoveField(
            model_name='time_is_moneyge',
            name='evening_word',
        ),
    ]
