# Generated by Django 2.1 on 2019-02-16 03:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0009_auto_20190216_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_is_moneyge',
            name='end_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time_is_moneyge',
            name='evening_overtime',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='time_is_moneyge',
            name='evening_word',
            field=models.CharField(max_length=150, null=True, verbose_name='お疲れ様の一言'),
        ),
    ]
