# Generated by Django 2.1 on 2019-02-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0010_auto_20190216_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_is_moneyge',
            name='overtime',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='time_is_moneyge',
            name='evening_word',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='お疲れ様の一言'),
        ),
        migrations.AlterField(
            model_name='time_is_moneyge',
            name='morning_word',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='おはようの一言'),
        ),
    ]
