# Generated by Django 2.1 on 2019-02-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0012_auto_20190217_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_is_moneyge',
            name='overtime',
            field=models.DurationField(null=True),
        ),
    ]
