# Generated by Django 2.1 on 2019-02-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0013_auto_20190219_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_is_moneyge',
            name='todays_overtime',
            field=models.DurationField(null=True),
        ),
    ]
