# Generated by Django 2.1 on 2019-03-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0014_time_is_moneyge_todays_overtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hourly_wage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('hourly_wage', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
