# Generated by Django 2.1 on 2019-03-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0015_hourly_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_is_moneyge',
            name='working_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='hourly_wage',
            name='hourly_wage',
            field=models.PositiveIntegerField(null=True, verbose_name='時給'),
        ),
    ]
