# Generated by Django 2.1 on 2019-04-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0016_auto_20190323_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paid_leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('paid_leave_date', models.DateField(null=True, verbose_name='有給休暇日')),
                ('memo', models.CharField(blank=True, max_length=150, null=True, verbose_name='メモ')),
            ],
        ),
    ]
