# Generated by Django 2.1 on 2019-04-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tim_app', '0018_auto_20190415_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_is_moneyge',
            name='user',
        ),
    ]
