# Generated by Django 2.1 on 2019-04-18 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tim_app', '0020_time_is_moneyge_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourly_wage',
            name='user',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paid_leave',
            name='user',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
